#
# Makefile for Linux arch/m68k/sun3x source directory
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definitions are now in the main makefile...

O_TARGET := sun3x.o
O_OBJS   := config.o time.o dvma.o sbus.o
OX_OBJS  := 

include $(TOPDIR)/Rules.make
