L_OBJS :=
LX_OBJS :=
M_OBJS :=
MX_OBJS :=
O_OBJS :=
OX_OBJS :=
L_TARGET :=
O_TARGET :=

O_OBJS += isdn_divert.o divert_procfs.o
O_TARGET := dss1_divert.o
M_OBJS += dss1_divert.o
OX_OBJS += divert_init.o

include $(TOPDIR)/Rules.make






