#
# Makefile for the USB serial device drivers.
#

O_TARGET	:= usb-serial.o
M_OBJS		:= usb-serial.o
O_OBJS		:= usbserial.o visor.o whiteheat.o ftdi_sio.o keyspan_pda.o omninet.o
MOD_LIST_NAME	:= USB_SERIAL_MODULES

include $(TOPDIR)/Rules.make

