# $Id: Makefile,v 1.3 1996/08/04 08:40:58 ecd Exp $
# Makefile for the Sparc low level /boot module.
#
# Copyright (C) 1995 David S. Miller (davem@caip.rutgers.edu)

all: boot

boot:
	@echo "Nothing special to be done for 'boot' on Linux/SPARC."

dep:

