#!/bin/sh

ME=`basename $0`

#UMOD=`lsmod | grep '^bp-mouse' | grep -v grep`
#if test "$UMOD"; then
#  echo "$ME: removing bp-mouse.o"
#  if ! rmmod bp-mouse; then
#    echo "$ME: cannot remove bp-mouse.o"
#    exit 1
#  fi
#fi

UPID=`ps aux | grep ohci-control | grep -v grep | awk '{print $2}'`
if test "$UPID"; then
  echo "$ME: killing $UPID"
  kill $UPID
fi

UMOD=`lsmod | grep '^usb-ohci' | grep -v grep`
if test "$UMOD"; then
  echo "$ME: removing usb-ohci.o"
  sleep 1
  if ! rmmod usb-ohci; then
    echo "$ME: cannot remove usb-ohci.o"
    exit 1
  fi
fi

dmesg -c > /dev/null

echo "$ME: starting usb-ohci.o"
insmod -m usb-ohci.o > usb-ohci.map

sleep 1
UPID=`ps aux | grep ohci-control | grep -v grep | awk '{print $2}'`
if test "$UPID"; then echo "$ME: ohci-control is pid $UPID" ; fi

