#
# Makefile for the Linux IrDA IrOBEX protocol layer.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definition is now in the main makefile...

#O_TARGET :=
O_OBJS	 := irobex.o
M_OBJS   := irobex.o

OX_OBJS  += 

include $(TOPDIR)/Rules.make

tar:
		tar -cvf /dev/f1 .
