#
# Makefile for some libs needed in the kernel.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#

L_TARGET := lib.a
L_OBJS   := errno.o ctype.o string.o vsprintf.o

include $(TOPDIR)/Rules.make
