#
# Makefile for the linux adfs filesystem routines.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (not a .c file).
#
# Note 2! The CFLAGS definitions are now in the main makefile.

O_TARGET := adfs.o
O_OBJS   := dir.o file.o inode.o map.o namei.o super.o
M_OBJS   := $(O_TARGET)

include $(TOPDIR)/Rules.make
