#
#       Copyright (C) 1997 Claus Heine.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#
# $Source: /homes/cvs/ftape-stacked/ftape/Makefile,v $
# $Revision: 1.4 $
# $Date: 1997/10/05 19:17:56 $
#
#      Makefile for the QIC-40/80/3010/3020 floppy-tape driver for
#      Linux.
#

#
#  This isn't used inside the kernel, only for my private development
#  version
#
ifndef TOPDIR
TOPDIR= ..
include $(TOPDIR)/MCONFIG
endif

SUB_DIRS     := 
MOD_SUB_DIRS := $(SUB_DIRS)
ALL_SUB_DIRS := $(SUB_DIRS) lowlevel zftape compressor

ifeq ($(CONFIG_FTAPE),y)
  O_TARGET := ftape.o
  SUB_DIRS += lowlevel
  O_OBJS   += lowlevel/ftape.o
else
  ifeq ($(CONFIG_FTAPE),m)
  MOD_SUB_DIRS += lowlevel
  endif
endif

ifeq ($(CONFIG_ZFTAPE),y)
  SUB_DIRS += zftape
  O_OBJS   += zftape/zftape.o
else
  ifeq ($(CONFIG_ZFTAPE),m)
  MOD_SUB_DIRS += zftape
  endif
endif

ifeq ($(CONFIG_ZFT_COMPRESSOR),y)
  SUB_DIRS += compressor
  O_OBJS   += compressor/zft-compressor.o
else
  ifeq ($(CONFIG_ZFT_COMPRESSOR),m)
  MOD_SUB_DIRS += compressor
  endif
endif

include $(TOPDIR)/Rules.make
