# Makefile for the act2000 ISDN device driver

# The target object and module list name.

O_TARGET	:= icn_drv.o

# Objects that export symbols.

export-objs	:=

# Object file lists.

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

# Each configuration option enables a list of files.

obj-$(CONFIG_ISDN_DRV_ICN)	+= icn.o

include $(TOPDIR)/Rules.make
