#!/bin/sh
#
#	Andre Hedrick <hedrick@astro.dyer.vanderbilt.edu>
#
#	The song goes, "I did it the hard way..........."
#

if [ ! -f /dev/hdi ]; then \
	echo "Making IDE4 Primary Devices hdi's"; \
	mknod /dev/hdi b 56 0; \
	mknod /dev/hdi1 b 56 1; \
	mknod /dev/hdi2 b 56 2; \
	mknod /dev/hdi3 b 56 3; \
	mknod /dev/hdi4 b 56 4; \
	mknod /dev/hdi5 b 56 5; \
	mknod /dev/hdi6 b 56 6; \
	mknod /dev/hdi7 b 56 7; \
	mknod /dev/hdi8 b 56 8; \
	mknod /dev/hdi9 b 56 9; \
	mknod /dev/hdi10 b 56 10; \
	mknod /dev/hdi11 b 56 11; \
	mknod /dev/hdi12 b 56 12; \
	mknod /dev/hdi13 b 56 13; \
	mknod /dev/hdi14 b 56 14; \
	mknod /dev/hdi15 b 56 15; \
	mknod /dev/hdi16 b 56 16; \
	chown root.disk /dev/hdi*; \
	chmod 660 /dev/hdi*; \
fi

if [ ! -f /dev/hdj ]; then \
	echo "Making IDE4 Secondary Devices hdj's"; \
	mknod /dev/hdj b 56 64; \
	mknod /dev/hdj1 b 56 65; \
	mknod /dev/hdj2 b 56 66; \
	mknod /dev/hdj3 b 56 67; \
	mknod /dev/hdj4 b 56 68; \
	mknod /dev/hdj5 b 56 69; \
	mknod /dev/hdj6 b 56 70; \
	mknod /dev/hdj7 b 56 71; \
	mknod /dev/hdj8 b 56 72; \
	mknod /dev/hdj9 b 56 73; \
	mknod /dev/hdj10 b 56 74; \
	mknod /dev/hdj11 b 56 75; \
	mknod /dev/hdj12 b 56 76; \
	mknod /dev/hdj13 b 56 77; \
	mknod /dev/hdj14 b 56 78; \
	mknod /dev/hdj15 b 56 79; \
	mknod /dev/hdj16 b 56 80; \
	chown root.disk /dev/hdj*; \
	chmod 660 /dev/hdj*; \
fi

if [ ! -f /dev/hdk ]; then \
	echo "Making IDE5 Primary Devices hdk's"; \
	mknod /dev/hdk b 57 0; \
	mknod /dev/hdk1 b 57 1; \
	mknod /dev/hdk2 b 57 2; \
	mknod /dev/hdk3 b 57 3; \
	mknod /dev/hdk4 b 57 4; \
	mknod /dev/hdk5 b 57 5; \
	mknod /dev/hdk6 b 57 6; \
	mknod /dev/hdk7 b 57 7; \
	mknod /dev/hdk8 b 57 8; \
	mknod /dev/hdk9 b 57 9; \
	mknod /dev/hdk10 b 57 10; \
	mknod /dev/hdk11 b 57 11; \
	mknod /dev/hdk12 b 57 12; \
	mknod /dev/hdk13 b 57 13; \
	mknod /dev/hdk14 b 57 14; \
	mknod /dev/hdk15 b 57 15; \
	mknod /dev/hdk16 b 57 16; \
	chown root.disk /dev/hdk*; \
	chmod 660 /dev/hdk*; \
fi

if [ ! -f /dev/hdl ]; then \
	echo "Making IDE5 Secondary Devices hdl's"; \
	mknod /dev/hdl b 57 64; \
	mknod /dev/hdl1 b 57 65; \
	mknod /dev/hdl2 b 57 66; \
	mknod /dev/hdl3 b 57 67; \
	mknod /dev/hdl4 b 57 68; \
	mknod /dev/hdl5 b 57 69; \
	mknod /dev/hdl6 b 57 70; \
	mknod /dev/hdl7 b 57 71; \
	mknod /dev/hdl8 b 57 72; \
	mknod /dev/hdl9 b 57 73; \
	mknod /dev/hdl10 b 57 74; \
	mknod /dev/hdl11 b 57 75; \
	mknod /dev/hdl12 b 57 76; \
	mknod /dev/hdl13 b 57 77; \
	mknod /dev/hdl14 b 57 78; \
	mknod /dev/hdl15 b 57 79; \
	mknod /dev/hdl16 b 57 80; \
	chown root.disk /dev/hdl*; \
	chmod 660 /dev/hdl*; \
fi

